<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <InternalsVisibleTo Include="KonturTests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="XmlConfig\Transforms\transform_without_group.xslt" />
    <EmbeddedResource Include="XmlConfig\Transforms\transform_with_group.xslt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="XmlConfig\Schemas\schema_pay.xsd" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Input\Data1.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Input\Data2.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Input\Data3.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
